#!/usr/bin/env sh
set -eu
exec 2>&1

# Wait for PHP_FPM to start
sleep 2
while true; do
	status=$(sv check php-fpm |grep run)
	if [[ ! -z $status ]]; then
		break
	fi
	sleep 1
done

logger -t runit "Starting nginx"

CMD=/usr/sbin/nginx
PID=/run/nginx/nginx.pid

install -d -o nginx -g nginx ${PID%/*}

${CMD} -t -q || exit 0

exec ${CMD} -g "pid $PID; daemon off;"
